/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a6da93c1-557f-421b-b266-8a31491bd1fc",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_RsnpFZbwi",
    "aws_user_pools_web_client_id": "174hhrvr45vq56mvs2g2h3gngj",
    "oauth": {}
};


export default awsmobile;
